# Overview

Title of project:"MADA Data Analysis Project"

Name of project author(s): Monica Chan

Name of project reviewer: Ehsan Suez


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

**
Precisely defined. I would personally want some details in introduction.**

### Summary assessment (PICK ONE, DELETE THE OTHERS)
**some contextualization and motivation**

## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

**I think all three aims were clearly presented here**

### Summary assessment

** question/hypotheses fully clear **



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

I think the data was clearly described, as well as the source of the data.

### Summary assessment

** source and overall structure of data well explained **



## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

I think you have done a great job with data wrangling. But I would suggest to add more comments for the readers to understand the way you were thinking while doing those particular steps.

### Summary assessment

** some weaknesses in wrangling and exploratory component **




## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

As per my knowledge, I think the analysis were pretty sound. And the way the analysis was presented, was great. There is always room for improvement in general, but I think you did great here.

### Summary assessment
* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The result presentation was good. Tables and figures were easy to understand.

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

I think the finding was discussed on a good level. You can add some more points there (detailing basically).

### Summary assessment

* strong, complete and clear discussion


## Further comments





# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

We;; structured, well labeled. Some files in the analysis folder could have been named a bit better. 

### Summary assessment

** mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders) **


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Overall well documented. But I would suggest having a clearer way of labeling files and organizing them.

### Summary assessment

* decently documented with some gaps



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

I was able to rerun the whole thing.


### Summary assessment
* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

WRITE YOUR FEEDBACK HERE

### Summary assessment

* strong level of thorougness


## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project._





