---
title: Project Review - Priyanka 
date: "`r file.mtime(knitr::current_input())`"
#bibliography: ../media/references.bib
output: 
  html_document:
    toc_depth: 3
    number_sections: true
---

# Overview

Title of project:

Name of project author(s): Monica Chan

Name of project reviewer: Priyanka Gannavarapu


# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component. 

Make sure your final document compiles/knits into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)


# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The project's context is clearly defined, as is the rationale for investigating this subject. The introduction can have some more information added( previous research)

### Summary assessment (PICK ONE, DELETE THE OTHERS)
*some contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

 The objective is based on the data. But clear hypothesis and questions are needed to make it more clear

### Summary assessment
*question/hypotheses somewhat explained


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

The data is clearly described, as is the source.

### Summary assessment
* Source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

 More explanation required for data cleaning. Detailed data wrangling would better to understand what is going on! Exploratory analysis should also be presented with more detailed explanation

### Summary assessment
* some weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

Data analysis layout has been given well. 

### Summary assessment

* Defensible but not optimal analysis 

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The flow of the results presented but needs more commentary and detailed description of what the findings are

### Summary assessment

* Results are presented ok, with room for improvement


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

Discussion section can be worked on a little. Presenting the finding and discussing the previous literature would be a solution. Checking if the results are in line or different from previous studies

### Summary assessment
* Minor parts wrong, missing or unclear


## Further comments

_Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project._



# Overall project content evaluation
Evaluate overall features of the project by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

The discussion portion can be worked on a little by mentioning previous research and comparing if the findings of this study are in line or is their any difference. If yes, what could the reasons be for the change in the results.

### Summary assessment
mostly clear, but some confusing parts



## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

 The documentation needs more clearer explanation and should be distinct to show what information is in which folder. Needs more detailed comments in the specific files

### Summary assessment
* decently documented with some gaps



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Reproducible results 


### Summary assessment
* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

Questions and hypothesis were addressed. More alternatives can be considered

### Summary assessment
* decent level of thoroughness


## Further comments

_Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project.

Great project considering the situation we are in. all results reproducible and no manual intervention was needed. 
