---
title: "Analysis 01 - All Data"
author: "MYC"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr) #for data processing
library(ggplot2) #for plotting
library(broom) #for cleaning up output from lm()
library(here) #for data loading/saving

```
Path to data
```{r Data}
#note the use of the here() package and not absolute paths
data_location <- here::here("data","processed_data","ALL.Data-20211029.rds")
#read and load data. 
ALL<- readRDS(data_location)
```

# Summarize the Data

```{r}
mysummary <- summary(ALL)
```

```{r}
#re-shape of a data frame (for easier saving/showing in manuscript)
summary_df <- data.frame(do.call(cbind, lapply(ALL, summary)))
```
```{r}
ALL%>%
  filter(Method!="PCR", Dilution!="NA")%>%
  group_by(Detector, Method, Dilution, Input)%>%
  summarise(n=n(),
            "Average Ct"= mean(Ct)
            )
```

```{r}
#save data frame table to file for later use in manuscript
summarytable_file <- here::here("products","Project_Parts","Part_3", "All.Summary.Table.rds")
saveRDS(summary_df, file = summarytable_file)
```

Make a scatterplot of data

```{r}
AllP1<-ALL %>% 
  filter(Method!="PCR", Tool=="SD"|Tool=="NEG.CTRL")%>%
  ggplot(aes(x=Dilution, y=Ct)) + 
  geom_jitter(aes(color=Method)) + 
  #we also add a glm line to it- using glm due to the continuous nature of the dilutions??
  geom_smooth(method='glm',alpha=0.2, aes(fill=Method, color=Method))+
  facet_grid(Detector~.)+
  scale_y_reverse()+
  geom_hline(yintercept=27, linetype="longdash", color = "orange")+ #CDC confirmed threshold
  geom_hline(yintercept=37, linetype="longdash", color = "blue")+ #General confirmed threshold
  labs(title="Serial Dilution Comparisons within ALL the data")

plot(AllP1)
```

```{r}
#save figure
figure_file = here("results","ALL-SD-Plot.png")
ggsave(filename = figure_file, plot=AllP1) 
```

```{r ALL Data fit and stat analysis}

```
######################################
#Data fitting/statistical analysis
######################################
```{r}
# fit glm.
# Ct~X= odds of Ct as response variable
ALL.glm.fit<-glm(Ct~Dilution+Detector+Method, data=ALL)
#look at fit
print(tidy(ALL.glm.fit))

step(ALL.glm.fit, test="LRT")
```
```{r}
# save fit results table  
table_file = here("results", "AllGLM.resulttable.rds")
saveRDS(ALL.glm.fit, file = table_file)

```




