---
title: "Analysis 02 - Phase 1 Data"
author: "MYC"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr) #for data processing
library(ggplot2) #for plotting
library(broom) #for cleaning up output from lm()
library(here) #for data loading/saving

```
Path to data
```{r Data}
#note the use of the here() package and not absolute paths
data_location <- here::here("data","processed_data","P1-20211029.rds")
#read and load data. 
P1<- readRDS(data_location)
```

# Summarize the Data

```{r}
P1mysummary <- summary(P1)
```

```{r}
#re-shape of a data frame (for easier saving/showing in manuscript)
P1summary_df <- data.frame(do.call(cbind, lapply(P1, summary)))
```
```{r}

```

```{r}
#save data frame table to file for later use in manuscript
summarytable_file <- here::here("products","Project_Parts","Part_3", "P1.Summary.Table.rds")
saveRDS(P1summary_df, file = summarytable_file)
```

Make a scatter plot of data
```{r}
P1P1<-P1 %>% 
  filter(Method!="PCR", Tool=="SD"|Tool=="NEG.CTRL")%>%
  ggplot(aes(x=Dilution, y=Ct)) + 
  geom_jitter(aes(color=Method)) + 
  #we also add a linear regression line to it
  geom_smooth(method='glm',alpha=0.2, aes(fill=Method, color=Method))+
  facet_grid(Detector~.)+
  scale_y_reverse()+geom_hline(yintercept=27, linetype="longdash", color = "orange")+ #CDC confirmed threshold
  geom_hline(yintercept=37, linetype="longdash", color = "blue")+ #General confirmed threshold
  labs(title="Serial Dilution Comparisons within Phase 1 data")

print(P1P1)
```
```{r}
#save figure
figure_file = here("results","P1-SD-Plot.png")
ggsave(filename = figure_file, plot=P1P1) 
```

```{r ALL Data fit and stat analysis}

```
######################################
#Data fitting/statistical analysis
######################################
```{r}
# fit glm.
# Ct~X= odds of Ct as response variable
P1.glm.fit<-glm(Ct~Dilution+Detector+Method, data=P1)
#look at fit
print(tidy(P1.glm.fit))

step(P1.glm.fit, test="LRT")
```
```{r}
# save fit results table  
table_file = here("results", "resulttable.rds")
saveRDS(lmtable, file = table_file)

```

