---
title: "Analysis 03 - Phase 2 Data"
author: "MYC"
date: "11/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr) #for data processing
library(ggplot2) #for plotting
library(broom) #for cleaning up output from lm()
library(here) #for data loading/saving

```
Path to data
```{r Data}
#note the use of the here() package and not absolute paths
data_location <- here::here("data","processed_data","P2-20211029.rds")
#read and load data. 
P2<- readRDS(data_location)
```

# Summarize the Data

```{r}
p2mysummary <- summary(P2)

print(p2mysummary)
```

```{r}
#re-shape of a data frame (for easier saving/showing in manuscript)
P2summary_df <- data.frame(do.call(cbind, lapply(P2, summary)))

print(P2summary_df)
```
```{r}
P2summary_df<-P2%>%
  filter(Dilution!="NA", Tool!="SD", Tool!="*.CTRL")%>%
  mutate(
    Ct.Cat = ifelse(Ct >=38,"Detected","Positive"),
    Ct.Cat=factor(Ct.Cat))%>%
  group_by(Dilution,Method,Ct.Cat)%>%
  summarise(n=n(),
            mean=mean(Ct))%>%
  arrange(Dilution,mean)
```

```{r}
#save data frame table to file for later use in manuscript
summarytable_file <- here::here("products","supplement","P2.Summary.Table.rds")
saveRDS(P2summary_df, file = summarytable_file)
```

```{r Table Best Ct comparing spike and surface recovery}
#Summary of Tool A compared to -1 Serial Dilution Recovery
P2.1Dilution.Summary<-P2%>%
  filter(Dilution=="-1")%>%
  mutate(
    Ct.Cat = ifelse(Ct >=38,"Detected","Positive"),
    Ct.Cat=factor(Ct.Cat))%>%
  group_by(Tool,Method,Ct.Cat)%>%
  summarise(n=n(),
            mean=mean(Ct))%>%
  arrange(mean)%>%
  na.omit(C.Cat)
```
```{r}
#save data frame table to file for later use in manuscript
summarytable_file <- here::here("products","supplement", "P2.-1Dilution.Table.rds")
saveRDS(P2.1Dilution.Summary, file = summarytable_file)
```
A difference of 2 Ct values when compared by methods for each tool type. CDC was better when directly extracted. NTP performed better during a spiked tool and surface recovery procedures. 
Ct loss between Spike and SS recovery are about 3 Ct values, equivalent to a log loss of copies.

Make a scatterplot of data

```{r warning=FALSE}
P2P1<-P2 %>% 
  filter(Method!="PCR", Tool=="SD"|Tool=="NEG.CTRL")%>%
  ggplot(aes(x=Dilution, y=Ct)) + 
  geom_jitter(aes(color=Method)) + 
  #we also add a linear regression line to it
  geom_smooth(method='glm',alpha=0.2, aes(fill=Method, color=Method))+
  facet_grid(Detector~.)+
  scale_y_reverse()+
  geom_hline(yintercept=27, linetype="longdash", color = "orange")+ #CDC confirmed threshold
  geom_hline(yintercept=37, linetype="longdash", color = "blue")+ #General confirmed threshold
  labs(title="Serial Dilution Comparisons within Phase 2 data")

print(P2P1)
```
```{r warning=FALSE}
#save figure
figure_file = here("results","P2-SD-Plot.png")
ggsave(filename = figure_file, plot=P2P1) 
```
