---
title: "Exploritory Modeling and Effects- P2 only"
author: "MYC"
date: "11/12/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #for data processing
library(here) #to set paths
library(tidymodels)      # for the recipes package, along with the rest of tidymodels
library(skimr)           # for variable summaries
library(rpart)
library(tune)
library(yardstick)
```
Path to data
```{r Data}
#note the use of the here() package and not absolute paths
data_location <- here::here("data","processed_data","P2-20211029.rds")
#read and load data. 
P2<- readRDS(data_location)

```
View proportions of the samples with Method
```{r}
P2%>%
  count(Method)%>%
  mutate(Proportions =n/sum(n))
```

View proportions of the samples within NTP method
```{r}
P2%>%
  filter(Method=="NTP")%>%
  count(Input)%>%
  mutate(Proportions =n/sum(n))
```

```{r}
P2%>%
  mutate(Norm.Ct=Ct/Input)
```

Data Splitting
Split into training and testing set
```{r}
# Fix the random numbers by setting the seed 
# This enables the analysis to be reproducible when random numbers are used 
set.seed(123)
# Put 3/4 of the data into the training set; this leaves 1/4 of the data to be used to test 
data_split <- initial_split(P2, prop = 3/4)
## Create data frames for the two sets:
train_data <- training(data_split)
test_data  <- testing(data_split)
```
Create CV object
```{r}
CV_train<- 
  vfold_cv(train_data, v=5, repeats= 5, strata = "Method")
```
Create a recipe
```{r}
fit_rec<-
  recipe(Method~., data = train_data)%>%
  step_dummy(all_nominal())
```
Null Model ? - do i need this?
```{r}
#Ct is a continuous outcome-- need to do RMSE as performance metric

RMSE_null_train<-sqrt(sum((train_data$Ct - mean(train_data$Ct))^2)/nrow(train_data))
RMSE_null_test<-sqrt(sum((test_data$Ct - mean(test_data$Ct))^2)/nrow(test_data))

print(RMSE_null_train)
print(RMSE_null_test)
```
Tree model setup
```{r}
tree_model<-decision_tree()%>%
  set_args(cost_complexity(tune(), tree_depth(tune(), min_n=tune())))%>%
  set_engine("rpart")%>%
  set_mode("regression")
```
```{r}
#set wf
tree_wf<- workflow()%>%
  add_model(tree_model)%>%
  add_recipe(fit_rec)
```
Tree Tuning
```{r}
#tuning grid
tree_grid <- dials::grid_regular(cost_complexity(), tree_depth(), min_n(), levels = 5)
#tune the model
tree_tune_res <- tree_wf %>% 
  tune::tune_grid(
    resamples = CV_train,
    grid = tree_grid,
    metrics = yardstick::metric_set(rmse) 
  )

```

Try LASSO
```{r}
#model
lasso_model <- linear_reg() %>%
  set_mode("regression") %>%           
  set_engine("glmnet") %>%
  set_args(penalty = tune(), mixture = 1) #mixture = 1 means we use the LASSO model

#workflow
lasso_wf <- workflow() %>%
  add_model(lasso_model) %>% 
  add_recipe(fit_rec)
```
LASSO Tune
```{r}
#tuning grid
lasso_reg_grid <- tibble(penalty = 10^seq(-3, 0, length.out = 30))

#tune model
lasso_tune_res <- lasso_wf %>% 
  tune_grid(resamples = CV_train,
            grid = lasso_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(rmse)
            )

```
```{r}
#see a plot of performance for different tuning parameters
lasso_tune_res %>% autoplot()
```

```{r}

Ct~Input*Method

lm_mod<-linear_reg()%>%
  set_engine("lm")

lm_fit<-  lm_mod%>%
  fit(Ct~Input*Method, data=P2)
lm_fit
```
```{r}
new_points<- expand.grid(initial_volume=20,
                         food_regime=)
```

```{r}
  P2%>%
  filter(Dilution!="NA", Tool!="SD", Tool!="*.CTRL")%>%
  mutate(
    Ct.Cat = ifelse(Ct >=38,"Detected","Positive"),
    Ct.Cat=factor(Ct.Cat))%>%
  group_by(Dilution,Method,Ct.Cat)%>%
  summarise(n=n(),
            mean=mean(Ct))%>%
  arrange(Dilution,mean)
```
```{r Table Best Ct comparing spike and surface recovery}
  P2%>%
  filter(Dilution=="-1")%>%
  mutate(
    Ct.Cat = ifelse(Ct >=38,"Detected","Positive"),
    Ct.Cat=factor(Ct.Cat))%>%
  group_by(Tool,Method,Ct.Cat)%>%
  summarise(n=n(),
            mean=mean(Ct))%>%
  arrange(mean)
```
